name: typed_json
description: A library intended to bring manual JSON serialization to the Dart projects of all scales.
version: 1.0.0
repository: https://github.com/npu3pak/typed_json

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  test: ^1.21.4
  lints: ^2.0.1
